# Generated by Django 5.2.4 on 2025-07-04 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='agencybusinessdetails',
            options={'verbose_name_plural': 'Agency business details'},
        ),
        migrations.AlterModelOptions(
            name='agencysettings',
            options={'verbose_name_plural': 'Agency settings'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User profiles'},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['agency', 'role'], name='agencies_us_agency__8f5fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_active'], name='agencies_us_is_acti_6680fb_idx'),
        ),
    ]
