# Generated by Django 5.2.4 on 2025-10-07 13:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agency commission percentage (e.g., 15.00 for 15%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agency commission/booking fee amount (auto-calculated if percentage is set)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guarantee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Guaranteed fee amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
