# Generated by Django 5.2.4 on 2025-07-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artistmember',
            options={'ordering': ['passport_name'], 'verbose_name': 'Artist Member', 'verbose_name_plural': 'Artist Members'},
        ),
        migrations.AlterModelOptions(
            name='artistnote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Artist Note', 'verbose_name_plural': 'Artist Notes'},
        ),
        migrations.AlterModelOptions(
            name='artistsociallinks',
            options={'verbose_name': 'Artist Social Links', 'verbose_name_plural': 'Artist Social Links'},
        ),
    ]
