# Generated by Django 5.2.4 on 2025-10-07 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artistmember_options_alter_artistnote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code for calendar and table visualization (e.g., #FF5733)', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color code (e.g., #FF5733)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
