# Generated by Django 5.2.4 on 2025-09-04 15:37

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0002_alter_agency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('promoter_name', models.CharField(max_length=255)),
                ('promoter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('promoter_phone', models.CharField(blank=True, max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('company_city', models.CharField(blank=True, max_length=100)),
                ('company_zipcode', models.CharField(blank=True, max_length=20)),
                ('company_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('promoter_type', models.CharField(choices=[('festival', 'Festival'), ('club', 'Club'), ('venue', 'Venue'), ('agency', 'Agency'), ('private', 'Private'), ('corporate', 'Corporate')], default='club', max_length=20)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(help_text='The agency that manages this promoter', on_delete=django.db.models.deletion.CASCADE, related_name='promoters', to='agencies.agency')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promoters', to='agencies.userprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_promoters', to='agencies.userprofile')),
            ],
            options={
                'verbose_name': 'Promoter',
                'verbose_name_plural': 'Promoters',
                'ordering': ['company_name', 'promoter_name'],
                'indexes': [models.Index(fields=['agency', 'promoter_name'], name='promoters_p_agency__5ab870_idx'), models.Index(fields=['agency', 'company_name'], name='promoters_p_agency__1e0395_idx'), models.Index(fields=['agency', 'promoter_type'], name='promoters_p_agency__ea44ab_idx'), models.Index(fields=['is_active'], name='promoters_p_is_acti_f45bf4_idx'), models.Index(fields=['created_at'], name='promoters_p_created_49a7f1_idx')],
                'unique_together': {('agency', 'promoter_email')},
            },
        ),
    ]
